### ISSUE TITLE
Not working with Airpod Pro

### ISSUE THREAD

**Issue by ppamorim** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#20]
Hi, my Airpods are connected and currently using it but the device never updates in the app. Please check this below:

<img width="368" alt="Screenshot 2020-07-17 at 14 50 53" src="https://user-images.githubusercontent.com/5521682/87793331-032c0c00-c83d-11ea-9a20-44a600def502.png">

**Comment by mohamed-arradi** [comment]
@ppamorim Hi, can you describe me if this happen always or time to time ? Is it possible to link a video or the issue ?. 

Why am I asking this ? 

- This software take few seconds to detect any connexion to bluetooth. Hence why there is a refresh devices action in order to refresh manually in case of failure. Did you try that ? It require a bluetooth connexion first before the software is updating. 

- An another issue could be that the app does not have the permission to fire Apple Events (you might have declined them) 

- The last but the almost impossible issue is that model verification is failing but that would be impossible. The app use that file to do the mapping https://gist.github.com/gabtastic/cdf5cd3adda1a0d2f9e12aae8d24b7e4

So if you can share me a video to show me few things like : 

- Airpods connexion via bluetooth to your mac
- wait 5 sec for the automatic refresh (did you get the Apple Event permission to the app ?) 
- Force the refresh 
- show me app permission

**Comment by trevorlasn** [comment]
+1

**Comment by mohamed-arradi** [comment]
@indreklasn Hi, 

is it a +1 related to the issue or that the comment solved it ?

**Comment by trevorlasn** [comment]
@mohamed-arradi Couldn't get it to work, with apple AirPods pro version.

**Comment by mohamed-arradi** [comment]
@indreklasn did you accept all permissions ? because Airpods Pro or normal it does not change anything. I have the airpods pro and it works perfectly.

Here a demo of the app (in japanese but you can use the auto-translated subtitles feature) . a guy explain who to use it properly 
https://www.youtube.com/watch?v=F8lBL62iYD4

**Comment by mohamed-arradi** [comment]
I assume after watching the demo video it has resolved the issue as no replies were given, so I took the initiative to close this issue unless additional elements are given.

**Comment by mohamed-arradi** [comment]
@indreklasn can you tell me if you have a better outcome with the new release version ? https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/releases/tag/1.0.15
