### ISSUE TITLE
Wrong and missing battery information

### ISSUE THREAD

**Issue by the-jan-peter** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#28]
The app is showing for my right AirPod 86% and for the left and case "--".

MacBook Pro (Retina 13 Zoll, Early 2015)
macOS 11.5.2

AirPods A1523
Firmware 6.8.8

**Comment by mohamed-arradi** [comment]
Hi @the-jan-peter, 

Thank you for raising your concern. Sometimes this issue can happen and it happen  with my own airpods too but very very rarely.

 this issue is a system wide "issue". Meaning that sometimes only right side or left side is sync as your Bluetooth connection itself fail to connect to both airpods (this can be checked on the bluetooth icon on the status bar).

Usually, when this happen, it  just requires you to put them back in the Airpods Case and put them out back again at the same times and things will get sorted automatically.  You also have a refresh devices action in the software.

Regarding the specific case of the Airpods Case battery information. Be aware that battery case can only be picked when Airpods Right and Left are not connected or when Airpods are within the case and the case is OPEN. You won't be able to see the battery case when airpods will be connected to your mac. 

I hope you managed to sort it out by yourself on this. I will put is as a note on the readme too.

Keep me posted if this is sorted in order to close the issue if successful.

**Comment by mohamed-arradi** [comment]
No response in 12 days. I consider the matter close. If the issue still arise, please open a new issue
