### ISSUE TITLE
Option to hide details in status bar

### ISSUE THREAD

**Issue by nilsreichardt** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#33]
Hi! Thanks for this application!

![image](https://user-images.githubusercontent.com/24459435/145691508-fc32ce86-8304-4055-b43a-6918db2c2923.png)

For me, it's a bit annoying to have so much information directly in the status bar, because I like it a bit more clean. I'm looking for a settings option, to disable the battery information in the status bar, so that I'm having only the icon. I would expect to enable this feature in the settings, but there is only one option (Launch on startup).

I'm this software on my MacBook M1 (macOS 12.0.1) and the version `2.2.1.100`.

**Comment by mohamed-arradi** [comment]
Hi @nilsreichardt,

Thanks for the feedback. However unless I misunderstand, this is the entire point of this software is to display the battery information at sight.

There will be no point in downloading this software if it is to do the same as the bluetooth icon that will display the battery values when you click on it.

Am I understanding correctly the reason of the setting you want ? 

Thanks

**Comment by nilsreichardt** [comment]
Maybe I'm misusing the main porpoise of the software 😅 My motivation to download the software was to get the information about the battery state of the case. Until now, I couldn't find any native option to get the battery state of the case. I'm able to get the battery state of left and right headphone, but not for the case on macOS. Your software gives me this option 💯

| macOS Audio Settings | AirpodsBattery-Monitor |
|--|--|
| ![image](https://user-images.githubusercontent.com/24459435/145710165-eae2175f-89b0-4710-acdf-f7bf83586e6e.png) |  ![image](https://user-images.githubusercontent.com/24459435/145710179-62eb6a1a-291b-4179-9412-04e9d12bd3cc.png) |

**Comment by mohamed-arradi** [comment]
Yeah I got it now @nilsreichardt.  However be careful, case battery are not always given or updated frequently by the system. That's why I assume they do not display it on Bluetooth section. 

Usually on opening, case is sending battery value for case, but then it is a one-off (unless airpods are still inside the case).

Regarding your setting, I still think it will deviate from the original purpose of my software. So I will not do this settings, however I can try to think about a smaller text information or "placement". Maybe horizontally if this is possible, I need to check :).
