### ISSUE TITLE
Mac OS Ventura and M2 Pro Support

### ISSUE THREAD

**Issue by bpqm** [mohamed-arradi/AirpodsBattery-Monitor-For-Mac#44]
This app will not launch on the Ventura (M2 Pro)

**Comment by mohamed-arradi** [comment]
@noname2001  Which app version are you using, are you using the latest release ? 

On my M2 Ventura machine I have no issue with it. 

Can you explain what happens when you launch it ? Any errors or alert from your system ?

Here the example with my machine

<img width="668" alt="Screenshot 2023-05-11 at 16 51 46" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/3295294/d59bee5c-efa5-45e3-8021-2020146399b9">

**Comment by taaneo** [comment]
Update Infomation

@mohamed-arradi I found the reason

if I close the hammerspoon, Airpods Battery Monitor can display on menubar

before

<img width="287" alt="image" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/9458206/fbfa882f-9ac8-43d2-99ca-c4738defc8a4">

after I close hammerspon

<img width="335" alt="image" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/9458206/1bc1d425-87ae-493c-949d-4ea845b80abe">


It's because my lua script add few menus in menubar, and there's not enough space to show it.
close the issue, and thank you for your app! :)

**Comment by taaneo** [comment]
@mohamed-arradi it's me again

the battery percentage display still doesn't work

but the  "connect to" button works, when I click it, my airpods connect to macbook, but there is no battery info

I try to click "refresh Devices" but still no battery infomation

FYI my airpods is the first generation airpods released in 2017

<img width="360" alt="image" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/9458206/7f56b94b-f321-4772-b61c-0ef038e1eab9">

**Comment by mohamed-arradi** [comment]
@noname2001 

Can you try to run this debug script on your laptop **after you** **have connected** your Airpods with your Macbook ?


[airpods-debug.sh.zip](https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/files/11500208/airpods-debug.sh.zip)
 
 To run it : 
```
Open a terminal
Go to where you stored the file cd my_file_directory (generally /Downloads)
sh airpods-debug.sh
```


You should see something coming between **some line E1 and E2** as per below .

 I need you to send me the content copied to the email: moha-dev-pro@proton.me
 
<img width="820" alt="Screenshot 2023-05-17 at 19 46 29" src="https://github.com/mohamed-arradi/AirpodsBattery-Monitor-For-Mac/assets/3295294/413be568-db9a-49d8-b877-4cb674acf723">

With that I will be able to know why your battery level is not read. Maybe the output on First generation is different. I cannot buy all generations :)

**Comment by taaneo** [comment]
@mohamed-arradi done : )

**Comment by mohamed-arradi** [comment]
@noname2001 Well received. Your output seems totally fine and is working fine on my end. 

I sent you an email with a specific debug version (that I will not release publicly) which contains some UI additional stuff to continue the debugging. 

As far as I saw, there is nothing wrong, and I suspect something related to either permissions in your Macbook or something else. 

Go over the email and let me know once you did the steps.

**Comment by taaneo** [comment]
@mohamed-arradi checked and reply to you, just close this issue, it seems works well now
